name: CD

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push to Github
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/iptv-proxy:${{ github.ref_name }}
            docker.pkg.github.com/${{ github.repository }}/iptv-proxy:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
